apiVersion: v1
kind: Service
metadata:
  name: cass-operator-webhook-service
  namespace: cass-operator
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager